cp ~/Desktop/mybpf/v2/restricted_files_utils.c .
cp ~/Desktop/mybpf/v2/restricted_files_utils.h .
cp ~/Desktop/mybpf/v2/config_utils.c .
cp ~/Desktop/mybpf/v2/config_utils.h .
cp ~/Desktop/mybpf/v2/event_utils.h .
cp ~/Desktop/mybpf/v2/get_event.c .
cp ~/Desktop/mybpf/v2/get_event.h .
cp ~/Desktop/mybpf/v2/main.c .
cp ~/Desktop/mybpf/v2/restrict_exec_utils.c .
cp ~/Desktop/mybpf/v2/restrict_exec_utils.h .
cp ~/Desktop/mybpf/v2/restrict_type_utils.c .
cp ~/Desktop/mybpf/v2/restrict_type_utils.h .
cp ~/Desktop/mybpf/v2/general_type_utils.c .
cp ~/Desktop/mybpf/v2/general_type_utils.h .
cp ~/Desktop/mybpf/v2/restrict_user_utils.c .
cp ~/Desktop/mybpf/v2/restrict_user_utils.h .
cp ~/Desktop/mybpf/v2/restrict_group_utils.c .
cp ~/Desktop/mybpf/v2/restrict_group_utils.h .
cp ~/Desktop/mybpf/v2/general_user_utils.c .
cp ~/Desktop/mybpf/v2/general_user_utils.h .
cp ~/Desktop/mybpf/v2/general_utils.h .
cp ~/Desktop/mybpf/v2/restrict_exec_open.bpf.c .
cp ~/Desktop/mybpf/v2/restrict_exec_read.bpf.c .
cp ~/Desktop/mybpf/v2/restrict_exec_write.bpf.c .
cp ~/Desktop/mybpf/v2/restrict_user_open.bpf.c .
cp ~/Desktop/mybpf/v2/restrict_user_read.bpf.c .
cp ~/Desktop/mybpf/v2/restrict_user_write.bpf.c .
cp ~/Desktop/mybpf/v2/get_path.h .